package esp.irt.courriers.entites;

import javax.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@AllArgsConstructor
public class Dossier {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String code;
    

    // Default (no-argument) constructor
    public Dossier() {
    }

    // Getters and setters can be generated by Lombok or added manually if not using Lombok
}
